# Generated by Django 5.1.2 on 2024-11-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('filename', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=120)),
                ('start', models.DateTimeField()),
                ('fps', models.PositiveSmallIntegerField()),
                ('frame_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClipStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveSmallIntegerField()),
                ('end', models.PositiveSmallIntegerField()),
                ('end_frame', models.ImageField(upload_to='')),
                ('merge_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.clipstub')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clip_stubs', to='detection.video')),
            ],
        ),
    ]
