# Generated by Django 5.1.2 on 2024-11-26 18:09

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('left', models.PositiveIntegerField(default=0)),
                ('top', models.PositiveIntegerField(default=0)),
                ('right', models.PositiveIntegerField(null=True)),
                ('bottom', models.PositiveIntegerField(null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='detection.camera')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sample', models.ImageField(upload_to='samples')),
                ('_detect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detect_tasks', to='detection.boundingbox')),
                ('exclude', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclude_tasks', to='detection.boundingbox')),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detection.importtask')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('filename', models.CharField(max_length=240, unique=True)),
                ('start', models.DateTimeField()),
                ('fps', models.PositiveSmallIntegerField()),
                ('frame_count', models.PositiveIntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='detection.importtask')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start', models.FloatField()),
                ('end', models.FloatField(null=True)),
                ('file', models.FileField(unique=True, upload_to='clips')),
                ('end_frame', models.ImageField(null=True, upload_to='')),
                ('merge_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.clip')),
                ('detect_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='detection.detecttask')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='detection.video')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(unique=True, upload_to='')),
                ('processed', models.BooleanField(default=False)),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='detection.importtask')),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.video')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
