# Generated by Django 5.1.2 on 2024-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='location',
            new_name='camera',
        ),
        migrations.AlterField(
            model_name='clipstub',
            name='end_frame',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
