# Generated by Django 5.1.2 on 2024-12-06 20:43

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='end',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='end_frame',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='merge_to',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='start',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='video',
        ),
        migrations.AddField(
            model_name='detecttask',
            name='view',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clip',
            name='file',
            field=models.FileField(null=True, unique=True, upload_to='clips'),
        ),
        migrations.CreateModel(
            name='ClipFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('start', models.FloatField()),
                ('end', models.FloatField(null=True)),
                ('end_frame', models.ImageField(null=True, upload_to='')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='detection.clip')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='detection.video')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
