# Generated by Django 5.1.2 on 2024-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_location_video_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipstub',
            name='end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clipstub',
            name='start',
            field=models.FloatField(),
        ),
    ]
