# Generated by Django 5.1.4 on 2024-12-09 19:16

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_remove_clip_end_remove_clip_end_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='DetectTask',
            name='import_task',
        ),
        migrations.RenameModel(
            old_name="ImportTask",
            new_name="VideoBatch",
        ),
        migrations.RenameModel(
            old_name="VideoProcessingTask",
            new_name="VideoHandler",
        ),
        migrations.RenameModel(
            old_name="DetectTask",
            new_name="Detection",
        ),
        migrations.RenameField("Clip", "detect_task", "detection"),
        migrations.RenameField("Detection", "_detect", "_detect_area"),
        migrations.RenameField("Detection", "exclude", "exclude_area"),
        migrations.RenameField("VideoHandler", "import_task", "batch"),
        migrations.RenameField("Video", "import_task", "batch"),
        migrations.AddField(
            model_name='Detection',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.camera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videobatch',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='detection.camera'),
        ),
        migrations.AlterField(
            model_name='videohandler',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='detection.videobatch'),
        ),
        migrations.AlterField(
            model_name='videohandler',
            name='video',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler', to='detection.video'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='_detect_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detection.boundingbox'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='exclude_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusions', to='detection.boundingbox'),
        ),
    ]
