# Generated by Django 5.1.4 on 2024-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_clip_detect_task_remove_importtask_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file',
            field=models.FileField(null=True, upload_to='clips'),
        ),
    ]
