# Generated by Django 5.1.4 on 2024-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_clip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file',
            field=models.FileField(null=True, upload_to='clips/'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='sample',
            field=models.ImageField(upload_to='samples/'),
        ),
    ]
